environment:
  matrix:
  - JULIAVERSION: "stable/win32"
  - JULIAVERSION: "stable/win64"
  - JULIAVERSION: "download/win32"
  - JULIAVERSION: "download/win64"

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile($("http://status.julialang.org/"+$env:JULIAVERSION), "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo(); Pkg.init();"
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/dpo/LinearOperators.jl.git\");"
  - C:\projects\julia\bin\julia -e "Pkg.clone(pwd(), \"Krylov\");"

test_script:
  - C:\projects\julia\bin\julia -e "Pkg.test(\"Krylov\")"
